### ISSUE TITLE
Project Oxford  dependency has not been specified in package.json

### ISSUE THREAD

**Issue by indcoder** [MumbaiHackerspace/Visage#10]
On  npm install getting the following error: 

Error: Cannot find module 'project-oxford'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\xxxxx\Documents\Projects\Visage\visage-isomorphic\src-server\ProcessAttendeeImage.js:5:18)
    at Object.<anonymous> (C:\Users\xxxxx\Documents\Projects\Visage\visage-isomorphic\server.js:19:48)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by indcoder** [comment]
Solved in this mega commit 

https://github.com/MumbaiHackerspace/Visage/commit/36ba8e32c481e630da47dfefbfe3d339de4ea7ab
